DESCRIPTION="Stub ebuild used to suppress other repo-level keyword output"
HOMEPAGE="https://github.com/pkgcore/pkgcheck"
SLOT="0"
LICENSE="BSD"
IUSE="matching probable test used use_expand_used"
RESTRICT="!test? ( test )"
