"""Default checks."""

# Please keep the imports and plugins sorted.
from .. import feeds, reporters
from ..checks import (
    cleanup, codingstyle, deprecated, dropped_keywords, git_checks, glsa,
    imlate, metadata_checks, metadata_xml, pkgdir_checks, python,
    profile_checks, repo_metadata, stablereq, unstable_only, visibility,
    whitespace,
)

pkgcore_plugins = {
    'check': [
        cleanup.RedundantVersionCheck,
        codingstyle.AbsoluteSymlinkCheck,
        codingstyle.BadInsIntoCheck,
        codingstyle.HttpsAvailableCheck,
        codingstyle.ObsoleteUriCheck,
        codingstyle.PathVariablesCheck,
        codingstyle.PortageInternalsCheck,
        deprecated.DeprecatedEclassCheck,
        dropped_keywords.DroppedKeywordsCheck,
        git_checks.GitCommitsCheck,
        glsa.TreeVulnerabilitiesCheck,
        imlate.ImlateCheck,
        metadata_checks.DependencyCheck,
        metadata_checks.DescriptionCheck,
        metadata_checks.IUSEMetadataCheck,
        metadata_checks.RequiredUSEMetadataCheck,
        metadata_checks.KeywordsCheck,
        metadata_checks.LicenseMetadataCheck,
        metadata_checks.LocalUSECheck,
        metadata_checks.MetadataCheck,
        metadata_checks.MissingSlotDepCheck,
        metadata_checks.RestrictsCheck,
        metadata_checks.SrcUriCheck,
        metadata_xml.CategoryMetadataXmlCheck,
        metadata_xml.PackageMetadataXmlCheck,
        pkgdir_checks.PkgDirCheck,
        profile_checks.ProfilesCheck,
        profile_checks.RepoProfilesCheck,
        python.PythonCheck,
        repo_metadata.GlobalUSECheck,
        repo_metadata.LicenseGroupsCheck,
        repo_metadata.ManifestConflictCheck,
        repo_metadata.ManifestCheck,
        repo_metadata.PackageUpdatesCheck,
        repo_metadata.UnusedEclassesCheck,
        repo_metadata.UnusedLicensesCheck,
        repo_metadata.UnusedMirrorsCheck,
        stablereq.StableRequestCheck,
        unstable_only.UnstableOnlyCheck,
        visibility.VisibilityCheck,
        whitespace.WhitespaceCheck,
        ],
    'transform': [
        feeds.CategoryToRepo,
        feeds.EbuildToVersion,
        feeds.PackageToCategory,
        feeds.PackageToRepo,
        feeds.VersionToCategory,
        feeds.VersionToEbuild,
        feeds.VersionToPackage,
        ],
    'reporter': [
        reporters.BinaryPickleStream,
        reporters.PickleStream,
        reporters.FancyReporter,
        reporters.NullReporter,
        reporters.StrReporter,
        reporters.JsonReporter,
        reporters.XmlReporter,
        ]
    }
