#!/usr/bin/env python
# Copyright: 2006 Marien Zwart <marienz@gentoo.org>
# License: BSD/GPL2

"""Minimal wrapper to launch pcheck."""

from pkgcore.util import commandline

from pkgcore_checks import pcheck


if __name__ == '__main__':
    commandline.main({None: (pcheck.OptionParser, pcheck.main)})
